export interface PlanetData {
  id: string;
  name: string;
  type: 'planet' | 'dwarf';
  diameter: number;
  distanceFromSun: number;
  orbitalPeriod: number;
  rotationPeriod: number;
  temperature: { min: number; max: number; avg: number };
  atmosphere: string;
  moons: number;
  color: string;
  emissive?: string;
  size3D: number;
  orbitRadius3D: number;
  texture: string;
  ringColor?: string;
  hasRings?: boolean;
  description: Record<string, string>;
  funFacts: Record<string, string[]>;
  composition: string;
  gravity: number;
  magneticField: boolean;
  discoveredBy?: string;
  discoveryYear?: number;
}

export const planets: PlanetData[] = [
  {
    id: 'mercury',
    name: 'Mercury',
    type: 'planet',
    diameter: 4879,
    distanceFromSun: 57.9,
    orbitalPeriod: 88,
    rotationPeriod: 58.6,
    temperature: { min: -180, max: 430, avg: 167 },
    atmosphere: 'Virtually none - thin exosphere of oxygen, sodium, hydrogen',
    moons: 0,
    color: '#b5b5b5',
    size3D: 0.38,
    orbitRadius3D: 8,
    texture: 'mercury',
    description: {
      en: 'The smallest planet and closest to the Sun. Mercury has virtually no atmosphere and experiences extreme temperature swings.',
      zh: '太阳系中最小的行星，也是距太阳最近的行星。水星几乎没有大气层，温差极大。',
      es: 'El planeta más pequeño y más cercano al Sol. Mercurio prácticamente no tiene atmósfera.',
      ja: '太陽に最も近い、最も小さい惑星。水星にはほとんど大気がなく、極端な温度変化があります。',
    },
    funFacts: {
      en: ['A year on Mercury is just 88 Earth days!', 'Mercury has no moons or rings', 'It has a large iron core'],
      zh: ['水星上的一年只有88个地球日！', '水星没有卫星或光环', '它有一个巨大的铁核'],
      es: ['¡Un año en Mercurio son solo 88 días terrestres!', 'Mercurio no tiene lunas ni anillos', 'Tiene un gran núcleo de hierro'],
      ja: ['水星の1年はわずか88地球日です！', '水星には衛星や環がありません', '大きな鉄の核を持っています'],
    },
    composition: 'Iron core (~75% of radius), silicate mantle',
    gravity: 3.7,
    magneticField: true,
  },
  {
    id: 'venus',
    name: 'Venus',
    type: 'planet',
    diameter: 12104,
    distanceFromSun: 108.2,
    orbitalPeriod: 225,
    rotationPeriod: -243,
    temperature: { min: 462, max: 462, avg: 464 },
    atmosphere: 'Dense CO₂ (96.5%), nitrogen (3.5%), sulfuric acid clouds',
    moons: 0,
    color: '#e8cda0',
    size3D: 0.95,
    orbitRadius3D: 12,
    texture: 'venus',
    description: {
      en: 'Often called Earth\'s twin due to similar size. Venus has a thick toxic atmosphere and is the hottest planet at 465°C.',
      zh: '因大小与地球相似而常被称为地球的"双胞胎"。金星有浓密的有毒大气层，表面温度高达465°C。',
      es: 'A menudo llamada la gemela de la Tierra por su tamaño similar. Venus tiene una atmósfera densa y tóxica.',
      ja: '地球と大きさが似ているため「双子」と呼ばれます。金星は厚い有毒な大気を持ち、最も暑い惑星です。',
    },
    funFacts: {
      en: ['Venus rotates backwards!', 'A day on Venus is longer than its year', 'Surface pressure is 90x Earth\'s'],
      zh: ['金星反向自转！', '金星上的一天比一年还长', '表面压力是地球的90倍'],
      es: ['¡Venus rota al revés!', 'Un día en Venus es más largo que su año', 'La presión superficial es 90 veces la de la Tierra'],
      ja: ['金星は逆回転しています！', '金星の1日は1年より長い', '表面気圧は地球の90倍'],
    },
    composition: 'Iron core, rocky mantle, thick CO₂ atmosphere',
    gravity: 8.87,
    magneticField: false,
  },
  {
    id: 'earth',
    name: 'Earth',
    type: 'planet',
    diameter: 12756,
    distanceFromSun: 149.6,
    orbitalPeriod: 365.25,
    rotationPeriod: 1,
    temperature: { min: -88, max: 58, avg: 15 },
    atmosphere: 'Nitrogen (78%), Oxygen (21%), Argon (0.9%), CO₂ (0.04%)',
    moons: 1,
    color: '#4da6ff',
    size3D: 1.0,
    orbitRadius3D: 16,
    texture: 'earth',
    description: {
      en: 'Our home planet and the only known world to harbor life. Earth has liquid water, a protective atmosphere, and a magnetic field.',
      zh: '我们的家园，也是已知唯一存在生命的星球。地球拥有液态水、保护性大气层和磁场。',
      es: 'Nuestro planeta hogar y el único mundo conocido que alberga vida. La Tierra tiene agua líquida y una atmósfera protectora.',
      ja: '私たちの故郷であり、生命が存在することが知られている唯一の惑星。地球には液体の水と保護大気があります。',
    },
    funFacts: {
      en: ['71% of Earth is covered in water', 'Earth is the densest planet', 'The core is as hot as the Sun\'s surface'],
      zh: ['地球71%的面积被水覆盖', '地球是密度最大的行星', '地核温度和太阳表面一样热'],
      es: ['El 71% de la Tierra está cubierta de agua', 'La Tierra es el planeta más denso', 'El núcleo está tan caliente como la superficie del Sol'],
      ja: ['地球の71%は水で覆われています', '地球は最も密度の高い惑星です', '核は太陽の表面と同じくらい暑い'],
    },
    composition: 'Iron-nickel core, silicate mantle, water atmosphere',
    gravity: 9.81,
    magneticField: true,
  },
  {
    id: 'mars',
    name: 'Mars',
    type: 'planet',
    diameter: 6792,
    distanceFromSun: 227.9,
    orbitalPeriod: 687,
    rotationPeriod: 1.03,
    temperature: { min: -140, max: 20, avg: -65 },
    atmosphere: 'CO₂ (95.3%), Nitrogen (2.7%), Argon (1.6%)',
    moons: 2,
    color: '#e07050',
    size3D: 0.53,
    orbitRadius3D: 21,
    texture: 'mars',
    description: {
      en: 'The Red Planet, named for its iron oxide surface. Mars has the largest volcano and deepest canyon in the solar system.',
      zh: '红色星球，因其表面的氧化铁而得名。火星拥有太阳系中最大的火山和最深的峡谷。',
      es: 'El Planeta Rojo, nombrado por su superficie de óxido de hierro. Marte tiene el volcán más grande del sistema solar.',
      ja: '酸化鉄の表面から名付けられた赤い惑星。火星には太陽系最大の火山と最深の峡谷があります。',
    },
    funFacts: {
      en: ['Olympus Mons is 3x taller than Everest', 'Mars has seasons like Earth', 'Sunsets on Mars are blue'],
      zh: ['奥林匹斯山是珠穆朗玛峰的3倍高', '火星像地球一样有四季', '火星上的日落是蓝色的'],
      es: ['Olympus Mons es 3 veces más alto que el Everest', 'Marte tiene estaciones como la Tierra', 'Los atardeceres en Marte son azules'],
      ja: ['オリンポス山はエベレストの3倍の高さ', '火星には地球のような四季があります', '火星の夕焼けは青い'],
    },
    composition: 'Iron core, silicate mantle, thin CO₂ atmosphere',
    gravity: 3.72,
    magneticField: false,
  },
  {
    id: 'jupiter',
    name: 'Jupiter',
    type: 'planet',
    diameter: 142984,
    distanceFromSun: 778.6,
    orbitalPeriod: 4331,
    rotationPeriod: 0.41,
    temperature: { min: -145, max: -110, avg: -110 },
    atmosphere: 'Hydrogen (90%), Helium (10%), ammonia crystals',
    moons: 95,
    color: '#d4a574',
    size3D: 3.5,
    orbitRadius3D: 32,
    texture: 'jupiter',
    description: {
      en: 'The largest planet — more massive than all other planets combined. Its Great Red Spot is a centuries-old storm larger than Earth.',
      zh: '太阳系最大的行星——质量超过其他所有行星的总和。它的大红斑是一个持续数百年的风暴，比地球还大。',
      es: 'El planeta más grande, más masivo que todos los demás planetas juntos. Su Gran Mancha Roja es una tormenta centenaria.',
      ja: '最大の惑星 — 他のすべての惑星を合わせたよりも大きい。大赤斑は何百年も続いている嵐です。',
    },
    funFacts: {
      en: ['Jupiter has at least 95 known moons', 'Its magnetic field is 20,000x stronger than Earth\'s', 'Jupiter could fit 1,300 Earths inside it'],
      zh: ['木星至少有95颗已知卫星', '其磁场强度是地球的20,000倍', '木星可以容纳1,300个地球'],
      es: ['Júpiter tiene al menos 95 lunas conocidas', 'Su campo magnético es 20,000 veces más fuerte', 'Júpiter podría contener 1,300 Tierras'],
      ja: ['木星には少なくとも95個の既知の衛星があります', '磁場は地球の20,000倍強い', '木星には地球1,300個が入る'],
    },
    composition: 'Hydrogen/helium gas giant, possible rocky core',
    gravity: 24.79,
    magneticField: true,
  },
  {
    id: 'saturn',
    name: 'Saturn',
    type: 'planet',
    diameter: 120536,
    distanceFromSun: 1433.5,
    orbitalPeriod: 10747,
    rotationPeriod: 0.45,
    temperature: { min: -178, max: -178, avg: -140 },
    atmosphere: 'Hydrogen (96%), Helium (3%), methane',
    moons: 146,
    color: '#f0d68a',
    size3D: 3.0,
    orbitRadius3D: 44,
    texture: 'saturn',
    hasRings: true,
    ringColor: '#f0d68a88',
    description: {
      en: 'Famous for its spectacular ring system made of billions of ice and rock particles. Saturn is less dense than water.',
      zh: '以其壮观的环系统闻名，由数十亿冰和岩石颗粒组成。土星的密度比水还低。',
      es: 'Famoso por su espectacular sistema de anillos de hielo y roca. Saturno es menos denso que el agua.',
      ja: '何十億もの氷と岩石の粒子からなる壮大な環で有名。土星は水より低い密度です。',
    },
    funFacts: {
      en: ['Saturn could float in water!', 'Its rings span 282,000 km but are only 10m thick', 'Saturn has 146 known moons'],
      zh: ['土星可以浮在水上！', '它的环跨度282,000公里但只有10米厚', '土星有146颗已知卫星'],
      es: ['¡Saturno podría flotar en agua!', 'Sus anillos miden 282,000 km pero solo 10m de grosor', 'Saturno tiene 146 lunas conocidas'],
      ja: ['土星は水に浮くことができます！', '環は282,000kmの幅ですが厚さは10m', '土星には146個の既知の衛星があります'],
    },
    composition: 'Hydrogen/helium, rocky/icy core, ice/rock rings',
    gravity: 10.44,
    magneticField: true,
  },
  {
    id: 'uranus',
    name: 'Uranus',
    type: 'planet',
    diameter: 51118,
    distanceFromSun: 2872.5,
    orbitalPeriod: 30589,
    rotationPeriod: -0.72,
    temperature: { min: -224, max: -224, avg: -195 },
    atmosphere: 'Hydrogen (83%), Helium (15%), Methane (2%)',
    moons: 28,
    color: '#7ec8e3',
    size3D: 2.0,
    orbitRadius3D: 56,
    texture: 'uranus',
    description: {
      en: 'An ice giant that rotates on its side with an axial tilt of 98°. Its blue-green color comes from methane.',
      zh: '一颗冰巨星，以98°的轴倾斜侧向旋转。其蓝绿色来自大气中的甲烷。',
      es: 'Un gigante de hielo que rota de lado con una inclinación de 98°. Su color azul-verde viene del metano.',
      ja: '98°の軸傾斜で横に回転する氷の巨大惑星。青緑色はメタンによるものです。',
    },
    funFacts: {
      en: ['Uranus was the first planet found with a telescope (1781)', 'It rolls around the Sun like a ball', 'Has 13 known rings'],
      zh: ['天王星是第一颗用望远镜发现的行星（1781年）', '它像球一样绕太阳滚动', '有13个已知光环'],
      es: ['Urano fue el primer planeta descubierto con telescopio (1781)', 'Rueda alrededor del Sol como una pelota', 'Tiene 13 anillos conocidos'],
      ja: ['天王星は望遠鏡で発見された最初の惑星（1781年）', 'ボールのように太陽の周りを転がります', '13個の既知の環があります'],
    },
    composition: 'Water/ammonia/methane ice, hydrogen/helium atmosphere',
    gravity: 8.87,
    magneticField: true,
    discoveredBy: 'William Herschel',
    discoveryYear: 1781,
  },
  {
    id: 'neptune',
    name: 'Neptune',
    type: 'planet',
    diameter: 49528,
    distanceFromSun: 4495.1,
    orbitalPeriod: 59800,
    rotationPeriod: 0.67,
    temperature: { min: -218, max: -218, avg: -200 },
    atmosphere: 'Hydrogen (80%), Helium (19%), Methane (1.5%)',
    moons: 16,
    color: '#4169e1',
    size3D: 1.9,
    orbitRadius3D: 66,
    texture: 'neptune',
    description: {
      en: 'The windiest planet with gusts up to 2,100 km/h. Neptune is the farthest planet and takes 165 years to orbit the Sun.',
      zh: '风速最快的行星，阵风可达2,100公里/小时。海王星是最远的行星，绕太阳一周需要165年。',
      es: 'El planeta más ventoso con ráfagas de hasta 2,100 km/h. Neptuno tarda 165 años en orbitar el Sol.',
      ja: '風速2,100km/hの嵐がある最も風の強い惑星。海王星は太陽を一周するのに165年かかります。',
    },
    funFacts: {
      en: ['Neptune was predicted mathematically before discovery', 'It has the strongest winds in the solar system', 'One Neptune year = 165 Earth years'],
      zh: ['海王星是在发现之前通过数学预测的', '它拥有太阳系中最强的风', '一个海王星年 = 165个地球年'],
      es: ['Neptuno fue predicho matemáticamente antes de su descubrimiento', 'Tiene los vientos más fuertes del sistema solar', 'Un año en Neptuno = 165 años terrestres'],
      ja: ['海王星は発見前に数学的に予測されました', '太陽系で最も強い風があります', '海王星の1年 = 165地球年'],
    },
    composition: 'Water/ammonia/methane ice, hydrogen/helium atmosphere',
    gravity: 11.15,
    magneticField: true,
    discoveredBy: 'Johann Galle',
    discoveryYear: 1846,
  },
  {
    id: 'pluto',
    name: 'Pluto',
    type: 'dwarf',
    diameter: 2376,
    distanceFromSun: 5906.4,
    orbitalPeriod: 90560,
    rotationPeriod: -6.39,
    temperature: { min: -240, max: -218, avg: -225 },
    atmosphere: 'Thin nitrogen, methane, carbon monoxide',
    moons: 5,
    color: '#c4a882',
    size3D: 0.3,
    orbitRadius3D: 76,
    texture: 'pluto',
    description: {
      en: 'A dwarf planet in the Kuiper Belt. Once the 9th planet, it was reclassified in 2006. Has a heart-shaped glacier.',
      zh: '柯伊伯带中的矮行星。曾经是第九大行星，2006年被重新分类。拥有一个心形冰川。',
      es: 'Un planeta enano en el Cinturón de Kuiper. Fue reclasificado en 2006. Tiene un glaciar en forma de corazón.',
      ja: 'カイパーベルトの準惑星。2006年に再分類されました。ハート型の氷河があります。',
    },
    funFacts: {
      en: ['Pluto has a heart-shaped glacier called Tombaugh Regio', 'It\'s smaller than Earth\'s Moon', 'Pluto and Charon are tidally locked'],
      zh: ['冥王星有一个心形冰川叫汤博区', '它比地球的月球还小', '冥王星和卡戎互相潮汐锁定'],
      es: ['Plutón tiene un glaciar en forma de corazón', 'Es más pequeño que la Luna de la Tierra', 'Plutón y Caronte están bloqueados por marea'],
      ja: ['冥王星にはハート型の氷河があります', '地球の月より小さい', '冥王星とカロンは潮汐固定されています'],
    },
    composition: 'Rock and ice, thin nitrogen atmosphere',
    gravity: 0.62,
    magneticField: false,
    discoveredBy: 'Clyde Tombaugh',
    discoveryYear: 1930,
  },
];

export const translations: Record<string, Record<string, string>> = {
  en: {
    title: 'Solar System Explorer',
    subtitle: 'Interactive 3D Space Learning',
    planets: 'Planets',
    dwarfPlanets: 'Dwarf Planets',
    info: 'Planet Info',
    quiz: 'Quiz',
    compare: 'Compare',
    realtime: 'Real-time',
    settings: 'Settings',
    speed: 'Speed',
    pause: 'Pause',
    play: 'Play',
    zoom: 'Zoom',
    focus: 'Focus',
    reset: 'Reset View',
    timeTravel: 'Time Travel',
    diameter: 'Diameter',
    distance: 'Distance from Sun',
    orbitalPeriod: 'Orbital Period',
    rotation: 'Rotation Period',
    temperature: 'Temperature',
    atmosphere: 'Atmosphere',
    moons: 'Moons',
    gravity: 'Surface Gravity',
    composition: 'Composition',
    magneticField: 'Magnetic Field',
    yes: 'Yes',
    no: 'No',
    funFacts: 'Fun Facts',
    vs: 'vs',
    moonPhase: 'Moon Phase',
    nextEclipse: 'Next Eclipse',
    issPosition: 'ISS Position',
    kidMode: 'Kid Mode',
    theme: 'Theme',
    language: 'Language',
    dark: 'Dark',
    light: 'Light',
    clickPlanet: 'Click a planet to learn more',
    days: 'days',
    years: 'years',
    km: 'km',
    million: 'M km',
    correct: 'Correct!',
    wrong: 'Wrong!',
    score: 'Score',
    next: 'Next',
    asteroidBelt: 'Asteroid Belt',
    comets: 'Comets',
    nightSky: 'Night Sky',
    screenshot: 'Screenshot',
    favorite: 'Favorite',
    narration: 'Narration',
    learningModules: 'Learning',
    showOrbits: 'Show Orbits',
    showLabels: 'Show Labels',
  },
  zh: {
    title: '太阳系探索者',
    subtitle: '交互式3D太空学习',
    planets: '行星',
    dwarfPlanets: '矮行星',
    info: '行星信息',
    quiz: '测验',
    compare: '比较',
    realtime: '实时数据',
    settings: '设置',
    speed: '速度',
    pause: '暂停',
    play: '播放',
    zoom: '缩放',
    focus: '聚焦',
    reset: '重置视角',
    timeTravel: '时间旅行',
    diameter: '直径',
    distance: '距太阳距离',
    orbitalPeriod: '公转周期',
    rotation: '自转周期',
    temperature: '温度',
    atmosphere: '大气层',
    moons: '卫星数',
    gravity: '表面重力',
    composition: '组成',
    magneticField: '磁场',
    yes: '有',
    no: '无',
    funFacts: '趣味知识',
    vs: '对比',
    moonPhase: '月相',
    nextEclipse: '下次日食',
    issPosition: '国际空间站位置',
    kidMode: '儿童模式',
    theme: '主题',
    language: '语言',
    dark: '暗色',
    light: '亮色',
    clickPlanet: '点击行星了解更多',
    days: '天',
    years: '年',
    km: '公里',
    million: '百万公里',
    correct: '正确！',
    wrong: '错误！',
    score: '得分',
    next: '下一题',
    asteroidBelt: '小行星带',
    comets: '彗星',
    nightSky: '夜空模式',
    screenshot: '截图',
    favorite: '收藏',
    narration: '语音',
    learningModules: '学习模块',
    showOrbits: '显示轨道',
    showLabels: '显示标签',
  },
  es: {
    title: 'Explorador del Sistema Solar',
    subtitle: 'Aprendizaje Espacial 3D Interactivo',
    planets: 'Planetas',
    dwarfPlanets: 'Planetas Enanos',
    info: 'Info del Planeta',
    quiz: 'Quiz',
    compare: 'Comparar',
    realtime: 'Tiempo Real',
    settings: 'Ajustes',
    speed: 'Velocidad',
    pause: 'Pausar',
    play: 'Reproducir',
    zoom: 'Zoom',
    focus: 'Enfocar',
    reset: 'Restablecer',
    timeTravel: 'Viaje en el Tiempo',
    diameter: 'Diámetro',
    distance: 'Distancia al Sol',
    orbitalPeriod: 'Período Orbital',
    rotation: 'Rotación',
    temperature: 'Temperatura',
    atmosphere: 'Atmósfera',
    moons: 'Lunas',
    gravity: 'Gravedad',
    composition: 'Composición',
    magneticField: 'Campo Magnético',
    yes: 'Sí',
    no: 'No',
    funFacts: 'Datos Curiosos',
    vs: 'vs',
    clickPlanet: 'Haz clic en un planeta para saber más',
    days: 'días',
    years: 'años',
    km: 'km',
    million: 'M km',
    correct: '¡Correcto!',
    wrong: '¡Incorrecto!',
    score: 'Puntuación',
    next: 'Siguiente',
    kidMode: 'Modo Niño',
    theme: 'Tema',
    language: 'Idioma',
    dark: 'Oscuro',
    light: 'Claro',
  },
  ja: {
    title: '太陽系エクスプローラー',
    subtitle: 'インタラクティブ3D宇宙学習',
    planets: '惑星',
    dwarfPlanets: '準惑星',
    info: '惑星情報',
    quiz: 'クイズ',
    compare: '比較',
    realtime: 'リアルタイム',
    settings: '設定',
    speed: '速度',
    pause: '一時停止',
    play: '再生',
    zoom: 'ズーム',
    focus: 'フォーカス',
    reset: 'リセット',
    timeTravel: 'タイムトラベル',
    diameter: '直径',
    distance: '太陽からの距離',
    orbitalPeriod: '公転周期',
    rotation: '自転周期',
    temperature: '温度',
    atmosphere: '大気',
    moons: '衛星数',
    gravity: '表面重力',
    composition: '組成',
    magneticField: '磁場',
    yes: 'あり',
    no: 'なし',
    funFacts: '豆知識',
    vs: '対',
    clickPlanet: '惑星をクリックして詳しく知る',
    days: '日',
    years: '年',
    km: 'km',
    million: '百万km',
    correct: '正解！',
    wrong: '不正解！',
    score: 'スコア',
    next: '次へ',
    kidMode: 'キッズモード',
    theme: 'テーマ',
    language: '言語',
    dark: 'ダーク',
    light: 'ライト',
  },
};

export const quizQuestions: Record<string, Array<{
  question: string;
  options: string[];
  correct: number;
  explanation: string;
}>> = {
  en: [
    { question: 'Which planet is closest to the Sun?', options: ['Venus', 'Mercury', 'Mars', 'Earth'], correct: 1, explanation: 'Mercury is the closest planet to the Sun at about 57.9 million km.' },
    { question: 'Which planet has the most moons?', options: ['Jupiter', 'Saturn', 'Uranus', 'Neptune'], correct: 1, explanation: 'Saturn has 146 known moons, the most of any planet!' },
    { question: 'Which planet is known as the Red Planet?', options: ['Venus', 'Jupiter', 'Mars', 'Mercury'], correct: 2, explanation: 'Mars is called the Red Planet due to iron oxide (rust) on its surface.' },
    { question: 'How long does it take Earth to orbit the Sun?', options: ['365.25 days', '365 days', '366 days', '364 days'], correct: 0, explanation: 'Earth takes approximately 365.25 days, which is why we have leap years!' },
    { question: 'Which planet has the Great Red Spot?', options: ['Mars', 'Saturn', 'Jupiter', 'Neptune'], correct: 2, explanation: 'Jupiter\'s Great Red Spot is a giant storm that has been raging for over 300 years.' },
    { question: 'Which planet rotates on its side?', options: ['Neptune', 'Uranus', 'Saturn', 'Venus'], correct: 1, explanation: 'Uranus has an axial tilt of 98°, essentially rolling around the Sun.' },
    { question: 'What is the largest planet in our solar system?', options: ['Saturn', 'Neptune', 'Jupiter', 'Uranus'], correct: 2, explanation: 'Jupiter is so large that all other planets could fit inside it.' },
    { question: 'Which planet could float in water?', options: ['Jupiter', 'Uranus', 'Neptune', 'Saturn'], correct: 3, explanation: 'Saturn has a density less than water (0.687 g/cm³), so it would float!' },
    { question: 'What type of planet is Pluto?', options: ['Gas giant', 'Ice giant', 'Dwarf planet', 'Terrestrial'], correct: 2, explanation: 'Pluto was reclassified as a dwarf planet in 2006 by the IAU.' },
    { question: 'Which planet has the strongest winds?', options: ['Jupiter', 'Saturn', 'Uranus', 'Neptune'], correct: 3, explanation: 'Neptune has winds up to 2,100 km/h, the fastest in the solar system.' },
  ],
  zh: [
    { question: '哪颗行星离太阳最近？', options: ['金星', '水星', '火星', '地球'], correct: 1, explanation: '水星是距太阳最近的行星，约5790万公里。' },
    { question: '哪颗行星的卫星最多？', options: ['木星', '土星', '天王星', '海王星'], correct: 1, explanation: '土星有146颗已知卫星，是太阳系中最多的！' },
    { question: '哪颗行星被称为红色星球？', options: ['金星', '木星', '火星', '水星'], correct: 2, explanation: '火星因其表面的氧化铁（铁锈）而被称为红色星球。' },
    { question: '地球绕太阳一周需要多长时间？', options: ['365.25天', '365天', '366天', '364天'], correct: 0, explanation: '地球大约需要365.25天，这就是为什么我们有闰年！' },
    { question: '哪颗行星有大红斑？', options: ['火星', '土星', '木星', '海王星'], correct: 2, explanation: '木星的大红斑是一个持续300多年的巨大风暴。' },
    { question: '哪颗行星侧躺着旋转？', options: ['海王星', '天王星', '土星', '金星'], correct: 1, explanation: '天王星的轴倾斜98°，基本上是绕太阳滚动。' },
    { question: '太阳系中最大的行星是？', options: ['土星', '海王星', '木星', '天王星'], correct: 2, explanation: '木星非常大，所有其他行星都可以装进去。' },
    { question: '哪颗行星可以浮在水上？', options: ['木星', '天王星', '海王星', '土星'], correct: 3, explanation: '土星的密度低于水（0.687 g/cm³），所以它会浮起来！' },
    { question: '冥王星是什么类型的行星？', options: ['气态巨行星', '冰巨行星', '矮行星', '类地行星'], correct: 2, explanation: '冥王星在2006年被IAU重新分类为矮行星。' },
    { question: '哪颗行星的风速最快？', options: ['木星', '土星', '天王星', '海王星'], correct: 3, explanation: '海王星的风速可达2,100公里/小时，是太阳系中最快的。' },
  ],
  es: [
    { question: '¿Qué planeta está más cerca del Sol?', options: ['Venus', 'Mercurio', 'Marte', 'Tierra'], correct: 1, explanation: 'Mercurio está a unos 57.9 millones de km del Sol.' },
    { question: '¿Qué planeta tiene más lunas?', options: ['Júpiter', 'Saturno', 'Urano', 'Neptuno'], correct: 1, explanation: '¡Saturno tiene 146 lunas conocidas!' },
    { question: '¿Qué planeta es conocido como el Planeta Rojo?', options: ['Venus', 'Júpiter', 'Marte', 'Mercurio'], correct: 2, explanation: 'Marte es llamado el Planeta Rojo por el óxido de hierro en su superficie.' },
    { question: '¿Cuánto tarda la Tierra en orbitar el Sol?', options: ['365.25 días', '365 días', '366 días', '364 días'], correct: 0, explanation: 'La Tierra tarda aproximadamente 365.25 días.' },
    { question: '¿Qué planeta tiene la Gran Mancha Roja?', options: ['Marte', 'Saturno', 'Júpiter', 'Neptuno'], correct: 2, explanation: 'La Gran Mancha Roja de Júpiter es una tormenta gigante.' },
  ],
  ja: [
    { question: '太陽に最も近い惑星は？', options: ['金星', '水星', '火星', '地球'], correct: 1, explanation: '水星は太陽から約5,790万kmの距離にあります。' },
    { question: '衛星が最も多い惑星は？', options: ['木星', '土星', '天王星', '海王星'], correct: 1, explanation: '土星には146個の既知の衛星があります！' },
    { question: '赤い惑星と呼ばれるのは？', options: ['金星', '木星', '火星', '水星'], correct: 2, explanation: '火星は表面の酸化鉄のため赤い惑星と呼ばれます。' },
    { question: '地球の公転周期は？', options: ['365.25日', '365日', '366日', '364日'], correct: 0, explanation: '地球は約365.25日で太陽を一周します。' },
    { question: '大赤斑がある惑星は？', options: ['火星', '土星', '木星', '海王星'], correct: 2, explanation: '木星の大赤斑は300年以上続く巨大な嵐です。' },
  ],
};

export const astronomicalEvents = [
  { date: '2026-03-30', event: { en: 'Solar Eclipse (Partial)', zh: '日偏食', es: 'Eclipse Solar Parcial', ja: '部分日食' }, visibility: 'North America, Europe' },
  { date: '2026-08-12', event: { en: 'Solar Eclipse (Total)', zh: '日全食', es: 'Eclipse Solar Total', ja: '皆既日食' }, visibility: 'Arctic, Greenland, Spain' },
  { date: '2026-09-14', event: { en: 'Lunar Eclipse (Partial)', zh: '月偏食', es: 'Eclipse Lunar Parcial', ja: '部分月食' }, visibility: 'Americas, Europe, Africa' },
  { date: '2026-11-21', event: { en: 'Jupiter Opposition', zh: '木星冲日', es: 'Oposición de Júpiter', ja: '木星の衝' }, visibility: 'Worldwide' },
  { date: '2027-01-16', event: { en: 'Mars Opposition', zh: '火星冲日', es: 'Oposición de Marte', ja: '火星の衝' }, visibility: 'Worldwide' },
];

export const cometData = [
  { name: 'Halley\'s Comet', nextPerihelion: '2061', period: '75-79 years', description: { en: 'The most famous periodic comet, visible from Earth every 75-79 years.' } },
  { name: 'Comet NEOWISE', nextPerihelion: '~6800 years', period: '~6800 years', description: { en: 'Discovered in 2020, this comet was visible to the naked eye.' } },
  { name: 'Comet Encke', nextPerihelion: '2026-11', period: '3.3 years', description: { en: 'Has the shortest known orbital period of any comet.' } },
];
